name: "Vercel Preview Alias"
description: "Alias Vercel Preview URLs"
inputs:
  vercel-token:
    description: "Vercel token e.g. https://vercel.com/account/tokens"
    required: true
  vercel-preview-url:
    required: true
    description: "Preview URL that you want to alias. If you have Vercel GitHub App, it's in the GitHub event e.g. github.event.deployment_status.target_url"
  vercel-target-url:
    required: true
    description: "Target URL that you want e.g. beta.example.com"
  vercel-scope:
    required: false
    description: "If in a Team, the scope of the team"
outputs:
  success:
    description: "Is true if the aliasing is successful"
runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "triangle"
  color: "white"
